- hosts:
  - jellyfin
  vars:
    ansible_user: root
    distro: ubuntu
    codename: jammy
  tasks:
  - name: change hostname
    shell: hostnamectl set-hostname jellyfin

  - name: install curl
    apt: 
      name: curl
      update_cache: yes

  - name: Create a directory music
    ansible.builtin.file:
      path: /music
      state: directory
      mode: '0755'

  - name: Create a directory filmes
    ansible.builtin.file:
      path: /filmes
      state: directory
      mode: '0755'

  - name: Create a directory series
    ansible.builtin.file:
      path: /series
      state: directory
      mode: '0755'

  - name: Create a directory anime
    ansible.builtin.file:
      path: /anime
      state: directory
      mode: '0755'

  - name: Create a directory cartoon
    ansible.builtin.file:
      path: /cartoon
      state: directory
      mode: '0755'


  - name: generate fstab
    shell: echo /dev/mapper/ubuntu--vg-ubuntu--lv / ext4 defaults 0 1 > /etc/fstab
  - name: generate fstab
    shell: echo /dev/vda2 /boot ext4 defaults 0 1 >> /etc/fstab
    
  - name: add music in fstab
    shell: echo music /music virtiofs defaults 0 0  >> /etc/fstab
  - name: add filmes in fstab
    shell: echo filmes /filmes virtiofs defaults 0 0  >> /etc/fstab
  - name: add series in fstab
    shell: echo series /series virtiofs defaults 0 0  >> /etc/fstab
  - name: add anime in fstab
    shell: echo anime /anime virtiofs defaults 0 0  >> /etc/fstab
  - name: add cartoon in fstab
    shell: echo cartoon /cartoon virtiofs defaults 0 0  >> /etc/fstab

  - name: install gnupg
    apt: 
      name: gnupg
      update_cache: yes
  
  - name: install keys
    shell: curl -fsSL https://repo.jellyfin.org/{{distro}}/jellyfin_team.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/jellyfin.gpg--batch --yes 
  
  - name: install sources
    template:
      src: jellyfin.sources
      dest: /etc/apt/sources.list.d/jellyfin.sources

  - name: install jellyfin
    apt:
      name: jellyfin
      update_cache: yes